-- Migration 006: Guest rate limits table + Storage RLS fixes
-- Run: supabase db push or manually apply

-- 1. Create guest_rate_limits table for DB-based rate limiting
CREATE TABLE IF NOT EXISTS guest_rate_limits (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ip_key TEXT NOT NULL UNIQUE,
  count INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_guest_rate_limits_ip_key ON guest_rate_limits(ip_key);

-- 2. Fix Storage RLS policies
-- Drop anonymous policies (security fix)
DROP POLICY IF EXISTS "Anonymous uploads" ON storage.objects;
DROP POLICY IF EXISTS "Anonymous deletes" ON storage.objects;

-- Create user-scoped policies
CREATE POLICY "Users can upload their own files"
  ON storage.objects
  FOR INSERT
  TO authenticated
  WITH CHECK (
    bucket_id = 'captures' 
    AND (storage.foldername(name))[1] = auth.uid()::text
  );

CREATE POLICY "Users can delete their own files"
  ON storage.objects
  FOR DELETE
  TO authenticated
  USING (
    bucket_id = 'captures' 
    AND (storage.foldername(name))[1] = auth.uid()::text
  );

CREATE POLICY "Anyone can view captures"
  ON storage.objects
  FOR SELECT
  TO public
  USING (bucket_id = 'captures');
